### ISSUE TITLE
Confirm Password field missing in User Registration Page

### ISSUE THREAD

**Issue by razabinashraf** [TinkerHub-CEC/Shelf#31]
@Dexters-Hub @HarikrishnanB

**Comment by Dexters-Hub** [comment]
I don't think that is necessary in MVP 😄

**Comment by farhan369** [comment]
i don't think it is necessary in any version .firstly i don't like it. secondly toggle button is good for checking. @razabinashraf

**Comment by razabinashraf** [comment]
okaaay
