### ISSUE TITLE
login page is always showing up

### ISSUE THREAD

**Issue by farhan369** [TinkerHub-CEC/Shelf#33]
closing the app or removing the app from the background after I finished login.it is showing again to log in even though I logged in before.
links that might to usefull
1.[1](https://stackoverflow.com/questions/64350345/flutter-why-does-the-login-page-appear-briefly-before-going-to-home-screen-eve)
2.[2](https://stackoverflow.com/questions/61796081/flutter-keep-user-logged-in-after-app-closes-and-reopen)

**Comment by Dexters-Hub** [comment]
aha okay - Let me check
