### ISSUE TITLE
Registration Page Snack Bar change

### ISSUE THREAD

**Issue by tgpaul** [TinkerHub-CEC/Shelf#35]
The present Snack Bar message after registering for the app is _"Registered Successfully"_ (or something along those lines). I would advise to change it to something like _"Registration almost complete. Check Email for a completion link. (Please do check 'Spam' also)"_.

Telling the User to check the Spam folder is also important because it is easily missed. (From experience). However, since it is a snack bar we will have to keep it as short as possible.

@Dexters-Hub

**Comment by Dexters-Hub** [comment]
text is changed to "Registration almost complete. Check the "Spam Folder" for an email to activate your account." @tgpaul

**Comment by farhan369** [comment]
why not closing only done. do I need to reopen?

**Comment by Dexters-Hub** [comment]
> why not closing only done. do I need to reopen?

nope
