### ISSUE TITLE
Admin Homepage - Multiple Headings

### ISSUE THREAD

**Issue by tgpaul** [TinkerHub-CEC/Shelf#36]
The present Admin Homepage has two headings, "Ongoing Events" and "Upcoming Events".

![issue](https://user-images.githubusercontent.com/68840617/132886715-eee1db6b-b7a0-4dfd-a660-981a972d0a2d.jpg)

@Dexters-Hub

**Comment by Dexters-Hub** [comment]
![com tinkerhubcec shelf_Screenshot_2021 09 13_18 18 18](https://user-images.githubusercontent.com/47777599/133086355-b6040515-330b-4cbc-8704-e5e0c0a8e665.png)


Fixed it @tgpaul
