### ISSUE TITLE
Long description not fully viewable.

### ISSUE THREAD

**Issue by Bin-Saleem** [TinkerHub-CEC/Shelf#48]
![Screenshot_20210912-214149](https://user-images.githubusercontent.com/64305274/132996640-e2a74480-c8f8-4e68-a5b7-5f10bb678938.jpg)

The long Description is not scrollable , so the lines after the third line is not visible.

**Comment by Bin-Saleem** [comment]
Also emoji is not supported . the gibberish in the starting is an emoji i presume.

**Comment by Dexters-Hub** [comment]
> Also emoji is not supported . the gibberish in the starting is an emoji i presume.

nope its just double quotes

**Comment by Dexters-Hub** [comment]
> ![Screenshot_20210912-214149](https://user-images.githubusercontent.com/64305274/132996640-e2a74480-c8f8-4e68-a5b7-5f10bb678938.jpg)
> 
> The long Description is not scrollable , so the lines after the third line is not visible.

This has been already fixed - due to some wrong merging the code got replaced with the old one.
