### ISSUE TITLE
Different button size in event details page.

### ISSUE THREAD

**Issue by Bin-Saleem** [TinkerHub-CEC/Shelf#49]
![Screenshot_20210912-214804](https://user-images.githubusercontent.com/64305274/132996827-70a1aed9-774a-457a-bf95-fccc6e8c213b.jpg)

The two button ( view delegates and verify attendance ) is of different size . It is due to the length of the text that is inside the button. I checked in the emulator and it is fine there ( it is same size ) , but in my phone it is different as shown above. Please make  the buttons the same size in all screen sizes.

**Comment by Bin-Saleem** [comment]
Also change the date format to DD-MM-YYYY

**Comment by Dexters-Hub** [comment]
button size fixed - i guess :D got to check it in real phone

**Comment by Dexters-Hub** [comment]
> Also change the date format to DD-MM-YYYY

💯 doing it now
