### ISSUE TITLE
Sign up page 

### ISSUE THREAD

**Issue by Vaishnav-OM** [TinkerHub-CEC/Shelf#50]
![Screenshot_1631514485](https://user-images.githubusercontent.com/56963231/133036051-07d83eb6-471c-4907-83b5-0fb1f57f80be.png)

First name not aligned.

**Comment by Dexters-Hub** [comment]
![com tinkerhubcec shelf_Screenshot_2021 09 13_18 34 47](https://user-images.githubusercontent.com/47777599/133088695-6a88b30e-d627-4832-83b3-f225f15b36b9.png)
fixed 🍡
