### ISSUE TITLE
'Register' button in 'Event Details' page

### ISSUE THREAD

**Issue by tgpaul** [TinkerHub-CEC/Shelf#57]
The 'Register' button in the 'Event Details' page needs to change once the User has registered to that event.  At present, the button does not change at all and hence could confuse the User.

A few suggestions would be, the button should :-
1. Dull-out the button once the registration has been completed.
2. Change the button to 'Registered' ( and Include a small note like "Enjoy the Event" or maybe something quirky like "Enjoy the Experience" 😄 ) .

@Dexters-Hub

**Comment by Dexters-Hub** [comment]
aysheri :smileinpain

**Comment by tgpaul** [comment]
Don't mean to make it worse but could you add one more condition to the 'if'. If no_of_registered_users = max_participants then also the button should become inaccessible. Ethu low priority aato.... I mean 'this', what I just said... not the actual issue raised.
😅...... 🏃
