### ISSUE TITLE
Event confirmation page is not responsive.

### ISSUE THREAD

**Issue by Bin-Saleem** [TinkerHub-CEC/Shelf#62]
![Screenshot_20210918-090135](https://user-images.githubusercontent.com/64305274/133893173-67939ddc-e539-46a5-bd57-05976499e39a.jpg)

There is overflow in name field and the admit 01 thing.
Please make it responsive.

**Comment by Dexters-Hub** [comment]
@Bin-Saleem Fixed the issue
